Models/contrat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrat
    {
        public int idcontrat { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public Nullable<decimal> montant_contrat { get; set; }
        public Nullable<int> idCar { get; set; }
        public Nullable<int> idreserv { get; set; }
    
        public virtual client client { get; set; }
        public virtual voiture voiture { get; set; }
        public virtual reservation reservation { get; set; }
    }
}

Controllers/contratsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarRental.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.xml;
using iTextSharp.text.html.simpleparser;
using iTextSharp.tool.xml;

namespace CarRental.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class contratsController : Controller
    {
        private carrentalEntities db = new carrentalEntities();

        
        // GET: reservations
        public ActionResult Index()
        {
            var user = User.Identity;
           
                ViewBag.Message = "ADMIN";
           
            var contrats = db.contrats.Include(c => c.client).Include(c => c.voiture).Include(c => c.reservation);

            return View(contrats.ToList());
        }
        public ActionResult Export(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(contrat);
        }
        [HttpPost]
        [ValidateInput(false)]
        public FileResult Export(string GridHtml)
        {
            using(MemoryStream stream = new System.IO.MemoryStream())
            {
                

                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 100f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);

                
                pdfDoc.Open();
                pdfDoc.AddHeader("Cars.ma", "Car.ma");
                // pdfDoc.Add(new Chunk(""));
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(),"application/pdf","Contrat.pdf");
            }
        }

        // GET: contrats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(contrat);
        }

        // GET: contrats/Create
        public ActionResult Create()
        {
            ViewBag.idclient = new SelectList(db.clients, "idclient", "nom_cl");
            ViewBag.idCar = new SelectList(db.voitures, "idcar", "immat");
            ViewBag.idreserv = new SelectList(db.reservations, "idreserv", "objectif_reserv");
            ViewBag.Message = "ADMIN";
            return View();
        }

        // POST: contrats/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idcontrat,idclient,date_debut,date_fin,montant_contrat,idCar,idreserv")] contrat contrat)
        {
            if (ModelState.IsValid)
            {
                db.contrats.Add(contrat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idclient = new SelectList(db.clients, "idclient", "nom_cl", contrat.idclient);
            ViewBag.idCar = new SelectList(db.voitures, "idcar", "immat", contrat.idCar);
            ViewBag.idreserv = new SelectList(db.reservations, "idreserv", "objectif_reserv", contrat.idreserv);
            ViewBag.Message = "ADMIN";
            return View(contrat);
        }

        // GET: contrats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            ViewBag.idclient = new SelectList(db.clients, "idclient", "nom_cl", contrat.idclient);
            ViewBag.idCar = new SelectList(db.voitures, "idcar", "immat", contrat.idCar);
            ViewBag.idreserv = new SelectList(db.reservations, "idreserv", "objectif_reserv", contrat.idreserv);
            ViewBag.Message = "ADMIN";
            return View(contrat);
        }

        // POST: contrats/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idcontrat,idclient,date_debut,date_fin,montant_contrat,idCar,idreserv")] contrat contrat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contrat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idclient = new SelectList(db.clients, "idclient", "nom_cl", contrat.idclient);
            ViewBag.idCar = new SelectList(db.voitures, "idcar", "immat", contrat.idCar);
            ViewBag.idreserv = new SelectList(db.reservations, "idreserv", "objectif_reserv", contrat.idreserv);
            ViewBag.Message = "ADMIN";
            return View(contrat);
        }

        // GET: contrats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(contrat);
        }

        // POST: contrats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            contrat contrat = db.contrats.Find(id);
            db.contrats.Remove(contrat);
            db.SaveChanges();
            ViewBag.Message = "ADMIN";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/contrats/Create.cshtml
@model CarRental.Models.contrat

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contrat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idclient, "idclient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idclient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_debut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_debut, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                @Html.ValidationMessageFor(model => model.date_debut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_fin, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                @Html.ValidationMessageFor(model => model.date_fin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montant_contrat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montant_contrat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.montant_contrat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCar, "idCar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCar", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idreserv, "idreserv", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idreserv", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idreserv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/contrats/Delete.cshtml
@model CarRental.Models.contrat

@{
    ViewBag.Title = "Delete";
}

<h2>Suppression</h2>

<h3>Voulez vous vraiment supprimer cet élément?</h3>
<div>
    <h4>Contrat</h4>
    <hr />
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/contrats/Details.cshtml
@model CarRental.Models.contrat

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Contrat</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.date_debut)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.date_debut)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.date_fin)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.date_fin)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.montant_contrat)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.montant_contrat)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.client.nom_cl)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.client.nom_cl)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.voiture.immat)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.voiture.immat)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.reservation.objectif_reserv)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.reservation.objectif_reserv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idcontrat }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/contrats/Edit.cshtml
@model CarRental.Models.contrat

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contrat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idcontrat)

        <div class="form-group">
            @Html.LabelFor(model => model.idclient, "idclient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idclient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idclient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_debut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_debut, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                @Html.ValidationMessageFor(model => model.date_debut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_fin, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
                @Html.ValidationMessageFor(model => model.date_fin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montant_contrat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montant_contrat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.montant_contrat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCar, "idCar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCar", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idreserv, "idreserv", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idreserv", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idreserv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Revenir", "Index")
</div>

Views/contrats/Export.cshtml
@model CarRental.Models.contrat
@{
    Layout = null;
}
@*<!Doctype html>
    <html>
    <head>
        <title>Contrat</title>
    </head>
    <body>
        <div id="Grid">
            <h4>Contrat</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.date_debut)
                </dt>

                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.date_debut)
                </dd>

                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.date_fin)
                </dt>

                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.date_fin)
                </dd>

                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.montant_contrat)
                </dt>

                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.montant_contrat)
                </dd>

                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.client.nom_cl)
                </dt>

                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.client.nom_cl)
                </dd>

                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.voiture.immat)
                </dt>

                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.voiture.immat)
                </dd>

                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.reservation.objectif_reserv)
                </dt>

                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.reservation.objectif_reserv)
                </dd>

            </dl>
        </div>
        @using (Html.BeginForm("Export", "contrats", FormMethod.Post))
        {
            <input type="hidden" name="GridHtml" />
            <input type="submit" id="btnSubmit" value="Export" />
        }
        <script src="~/Content/vendor/jquery/jquery.min.js"></script>
        <script>
            $(function () {
                $("#btnSubmit").click(function () {
                    $("input[name='GridHtml']").val($("#Grid").html());
                });
            });
        </script>
    </body>
    </html>*@
<!Doctype html>
<html>
<head>
    <title>Contrat de location</title>
</head>
<body>
    <div id="Grid">
        <div text-align="center">
            <h1 text-align="center">Contrat de location de voiture</h1>
        </div>
        <table>
            <tr>
                <td>
                    <h2>Infos du Vehicule :</h2>
                    <table>
                        <tr><td><strong>Immatriculation :</strong></td><td> @Html.DisplayFor(model => model.voiture.immat)</td></tr>
                        <tr><td><strong>Nom modèle :</strong></td><td> @Html.DisplayFor(model => model.voiture.modele.nom_modele)</td></tr>
                        <tr><td><strong>Carburant :</strong></td><td> @Html.DisplayFor(model => model.voiture.category.libelle_cat)</td></tr>
                        <tr><td><strong>Prix par jour :</strong></td><td> @Html.DisplayFor(model => model.voiture.prixJour)</td></tr>
                        <tr><td><strong> N° Carte grise :</strong></td><td> @Html.DisplayFor(model => model.voiture.carte_grise)</td></tr>
                        <tr><td><strong>Nombre de places :</strong></td><td> @Html.DisplayFor(model => model.voiture.nbplace)</td></tr>
                        <tr><td><strong>Nombre de portes :</strong></td><td> @Html.DisplayFor(model => model.voiture.nbporte)</td></tr>
                    </table>

                </td>
                <td>
                    <h2>Infos du Client :</h2>
                    <table>
                        <tr><td><strong>CIN :</strong></td><td> @Html.DisplayFor(model => model.client.CIN_cl)</td></tr>
                        <tr><td><strong>Nom :</strong></td><td> @Html.DisplayFor(model => model.client.nom_cl)</td></tr>
                        <tr><td><strong>Prénom :</strong></td><td> @Html.DisplayFor(model => model.client.prenom_cl)</td></tr>
                        <tr><td><strong>Adresse :</strong></td><td> @Html.DisplayFor(model => model.client.adresse_cl)</td></tr>
                        <tr><td><strong>E-mail :</strong></td><td> @Html.DisplayFor(model => model.client.email)</td></tr>
                        <tr><td><strong>Tel :</strong></td><td> @Html.DisplayFor(model => model.client.tel_cl)</td></tr>
                    </table>

                </td>
            </tr>
            
            <tr>
                <td>
                    <h2>Infos de la Reservation :</h2>
                    <table>
                        <tr><td><strong>Objectif de reservation :</strong></td><td> @Html.DisplayFor(model => model.reservation.objectif_reserv)</td></tr>
                        <tr><td><strong>Date début de la reservation :</strong></td><td> @Html.DisplayFor(model => model.reservation.date_debut)</td></tr>
                        <tr><td><strong>Date Fin de la reservation :</strong></td><td> @Html.DisplayFor(model => model.reservation.date_fin)</td></tr>

                    </table>

                </td>
                <td>
                    <h2>Infos du Contrat :</h2>
                    <table>
                        <tr><td><strong>Date debut contrat :</strong></td><td> @Html.DisplayFor(model => model.date_debut)</td></tr>
                        <tr><td><strong>Date fin contrat :</strong></td><td> @Html.DisplayFor(model => model.date_fin)</td></tr>
                        <tr><td><strong>Montant total à payer :</strong></td><td> @Html.DisplayFor(model => model.montant_contrat)</td></tr>

                    </table>

                </td>
            </tr>
            <tr>
                <td><h2>Signature du client</h2></td>
                <td><h2>Signature et Cachet de l'agence</h2></td>
            </tr>
            
        </table>
    </div>
     @using (Html.BeginForm("Export", "contrats", FormMethod.Post))
        {
            <input type="hidden" name="GridHtml" />
            <input type="submit" id="btnSubmit" value="Export" />
        }
        <script src="~/Content/vendor/jquery/jquery.min.js"></script>
        <script>
            $(function () {
                $("#btnSubmit").click(function () {
                    $("input[name='GridHtml']").val($("#Grid").html());
                });
            });
        </script>
</body>
</html>

Views/contrats/Index.cshtml
@model IEnumerable<CarRental.Models.contrat>

@{
    ViewBag.Title = "Index";
}


<h2>Contrats</h2>

<span class="btn btn-light">
    <i class="fas fa-plus"></i>
    @Html.ActionLink("Create New", "Create", new { @style = "color:#fff;" })
</span>



<div class="container-fluid">
    <!-- DataTales Example -->

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                Liste des Marques
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%"
                       cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Client
                            </th>
                            <th>
                                Montant total
                            </th>
                            <th>
                                Mat. voiture
                            </th>
                            <th>Actions</th>

                        </tr>
                    <tfoot>
                        <tr>

                            <th>
                                Client
                            </th>
                            <th>
                                Montant total
                            </th>
                            <th>
                                Mat. voiture
                            </th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.client.nom_cl)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.montant_contrat)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.voiture.immat)
                                </td>
                                <td>

                                    <span class="btn btn-primary text-light"><i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.idcontrat }, new { @style = "color:#fff;" })</span>
                                    <span class="btn btn-success"><i class="fas fa-list"></i>@Html.ActionLink("Details", "Details", new { id = item.idcontrat }, new { @style = "color:#fff;" }) </span>
                                    <span class="btn btn-danger"><i class="fas fa-trash-alt"></i>@Html.ActionLink("Delete", "Delete", new { id = item.idcontrat }, new { @style = "color:#fff;" })</span>
                                    <span class="btn btn-warning"><i class="fas fa-trash-alt"></i>@Html.ActionLink("Export", "Export", new { id = item.idcontrat }, new { @style = "color:#fff;" })</span>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->