Models/voiture.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voiture()
        {
            this.reservations = new HashSet<reservation>();
            this.contrats = new HashSet<contrat>();
        }
    
        public int idcar { get; set; }
        public Nullable<int> idcat { get; set; }
        public Nullable<int> idmodele { get; set; }
        public string immat { get; set; }
        public string carte_grise { get; set; }
        public Nullable<int> nbporte { get; set; }
        public Nullable<int> nbplace { get; set; }
        public Nullable<int> puissance { get; set; }
        public Nullable<System.DateTime> date_aquis { get; set; }
        public Nullable<System.DateTime> datedebut_assurance { get; set; }
        public Nullable<System.DateTime> datefin_assurance { get; set; }
        public Nullable<decimal> cout_assurance { get; set; }
        public string typecarburant { get; set; }
        public Nullable<decimal> prixJour { get; set; }
    
        public virtual category category { get; set; }
        public virtual modele modele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrat> contrats { get; set; }
    }
}

Controllers/voituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarRental.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CarRental.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class voituresController : Controller
    {
        private carrentalEntities db = new carrentalEntities();
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());

                if (s[0].ToString() == "ADMIN")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
        // GET: reservations
        public ActionResult Index()
        {
            var user = User.Identity;
            if (isAdminUser())
            {
                ViewBag.Message = "ADMIN";
            }
            else
            {

                ViewBag.Message = user.Name;
            }
            var voitures = db.voitures.Include(v => v.category).Include(v => v.modele);
            return View(voitures.ToList());
        }

        // GET: voitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            Photo photo = db.Photos.Find(id);
            voiture.OnePhoto = photo;
            if (voiture == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(voiture);
        }

        // GET: voitures/Create
        public ActionResult Create()
        {
            ViewBag.idcat = new SelectList(db.categories, "idcat", "libelle_cat");
            ViewBag.idmodele = new SelectList(db.modeles, "idmodele", "nom_modele");
            ViewBag.Message = "ADMIN";
            return View();
        }

        // POST: voitures/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(voiture voiture)
        {
            Photo photo = new Photo();
            string filename = Path.GetFileNameWithoutExtension(voiture.ImageFile.FileName);
            string extension = Path.GetExtension(voiture.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssff") + extension;
            photo.ImagePath = "~/Image/"+filename;
            filename = Path.Combine(Server.MapPath("~/Image/"), filename);
            voiture.ImageFile.SaveAs(filename);
            photo.idCar = voiture.idcar;
            if (ModelState.IsValid)
            {
                db.voitures.Add(voiture);
                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Message = "ADMIN";
            ViewBag.idcat = new SelectList(db.categories, "idcat", "libelle_cat", voiture.idcat);
            ViewBag.idmodele = new SelectList(db.modeles, "idmodele", "nom_modele", voiture.idmodele);
            return View(voiture);
        }

        // GET: voitures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcat = new SelectList(db.categories, "idcat", "libelle_cat", voiture.idcat);
            ViewBag.idmodele = new SelectList(db.modeles, "idmodele", "nom_modele", voiture.idmodele);
            ViewBag.Message = "ADMIN";
            return View(voiture);
        }

        // POST: voitures/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idcar,idcat,idmodele,immat,carte_grise,nbporte,nbplace,puissance,date_aquis,datedebut_assurance,datefin_assurance,cout_assurance,typecarburant,photo")] voiture voiture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(voiture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idcat = new SelectList(db.categories, "idcat", "libelle_cat", voiture.idcat);
            ViewBag.idmodele = new SelectList(db.modeles, "idmodele", "nom_modele", voiture.idmodele);
            ViewBag.Message = "ADMIN";
            return View(voiture);
        }

        // GET: voitures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(voiture);
        }
        public ActionResult ReservationsByCar(int? id)
        {
            ViewBag.Message = "ADMIN";
            return View(db.ReservationByCar(id).ToList());
        }




        // POST: voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            voiture voiture = db.voitures.Find(id);
            db.voitures.Remove(voiture);
            db.SaveChanges();
            ViewBag.Message = "ADMIN";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/voitures/Create.cshtml
@model CarRental.Models.voiture

@{
    ViewBag.Title = "Create";
}

<h2>Ajouter</h2>

@using (Html.BeginForm("Create","voitures",FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Voiture</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.idcat, "idcat", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idcat", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idcat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idmodele, "idmodele", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idmodele", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idmodele, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.prixJour, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.prixJour, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.prixJour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.immat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.immat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.immat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.carte_grise, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.carte_grise, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.carte_grise, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nbporte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nbporte, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nbporte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nbplace, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nbplace, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nbplace, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.puissance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.puissance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.puissance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date_aquis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_aquis, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
            @Html.ValidationMessageFor(model => model.date_aquis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.datedebut_assurance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.datedebut_assurance, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
            @Html.ValidationMessageFor(model => model.datedebut_assurance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.datefin_assurance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.datefin_assurance, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD" } })
            @Html.ValidationMessageFor(model => model.datefin_assurance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cout_assurance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cout_assurance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cout_assurance, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="file" name="ImageFile" />        
        </div>
    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary"><i class="fas fa-save">&nbsp;Enregistrer</i></button>
        <button type="reset" class="btn btn-danger"><i class="fas fa-undo">&nbsp;Annuler</i></button>
    </div>
</div>
}

<div>
    @Html.ActionLink("Revenir à la liste", "Index")
</div>

Views/voitures/Delete.cshtml
@model CarRental.Models.voiture

@{
    ViewBag.Title = "Delete";
}

<h2>Supprimer</h2>

<h3>Etes-vous sure de vouloir supprimer cet élément?</h3>
<div>
    <h4>Voiture</h4>
    <hr />
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
            @Html.ActionLink("Revenir à la liste", "Index")
        </div>
    }
</div>

Views/voitures/Details.cshtml
@model CarRental.Models.voiture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Voiture</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.immat)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.immat)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.carte_grise)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.carte_grise)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.prixJour)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.prixJour)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.nbporte)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.nbporte)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.nbplace)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.nbplace)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.puissance)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.puissance)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.date_aquis)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.date_aquis)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.datedebut_assurance)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.datedebut_assurance)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.datefin_assurance)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.datefin_assurance)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.cout_assurance)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.cout_assurance)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.category.libelle_cat)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.category.libelle_cat)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.modele.nom_modele)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.modele.nom_modele)
        </dd>
        <dt class="col-sm-3">
            Photo
        </dt>

        <dd class="col-sm-9">
            <img src="@Url.Content(Model.OnePhoto.ImagePath)" alt="xx" width="250" height="250" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/voitures/Edit.cshtml
@model CarRental.Models.voiture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Voiture</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idcar)

    <div class="form-group">
        @Html.LabelFor(model => model.idcat, "idcat", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idcat", null, htmlAttributes: new { @class = "form-control form-control-user" })
            @Html.ValidationMessageFor(model => model.idcat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idmodele, "idmodele", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idmodele", null, htmlAttributes: new { @class = "form-control form-control-user" })
            @Html.ValidationMessageFor(model => model.idmodele, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.immat, new { @class = "form-control form-control-user", placeholder = "Immatriculation" })
            @Html.ValidationMessageFor(model => model.immat, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.prixJour, new { @class = "form-control form-control-user", placeholder = "Prix par jour" })
            @Html.ValidationMessageFor(model => model.prixJour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.carte_grise, new { @class = "form-control form-control-user", placeholder = "Carte grise" })
            @Html.ValidationMessageFor(model => model.carte_grise, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nbporte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nbporte, new { @class = "form-control form-control-user", placeholder = "Nb. Portes" })
            @Html.ValidationMessageFor(model => model.nbporte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.nbplace, new { @class = "form-control form-control-user", placeholder = "Nb. Places" })
            @Html.ValidationMessageFor(model => model.nbplace, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.puissance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.puissance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.puissance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date_aquis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_aquis, new { @class = "form-control form-control-user", placeholder = "YYYY-MM-DD" })
            @Html.ValidationMessageFor(model => model.date_aquis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.datedebut_assurance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.datedebut_assurance, new { @class = "form-control form-control-user", placeholder = "YYYY-MM-DD" })
            @Html.ValidationMessageFor(model => model.datedebut_assurance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.datefin_assurance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.datefin_assurance, new { @class = "form-control form-control-user", placeholder = "YYYY-MM-DD" })
            @Html.ValidationMessageFor(model => model.datefin_assurance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cout_assurance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cout_assurance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cout_assurance, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary"><i class="fas fa-save">&nbsp;Enregistrer</i></button>
        <button type="reset" class="btn btn-danger"><i class="fas fa-undo">&nbsp;Annuler</i></button>
    </div>
</div>
}

<div>
    @Html.ActionLink("Revenir à la liste", "Index")
</div>

Views/voitures/Index.cshtml
@model IEnumerable<CarRental.Models.voiture>

@{
    ViewBag.Title = "Index";
}


<h2>Voitures</h2>

    <span class="btn btn-outline-primary">
        <i class="fas fa-plus"></i>
        @Html.ActionLink("Ajouter", "Create", new { @style = "color:#fff;" })
    </span>



    <div class="container-fluid">
        <!-- DataTales Example -->

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">
                    Liste des Marques
                </h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%"
                           cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    Matricule
                                </th>
                                <th>
                                    Modele
                                </th>
                                <th>
                                    Categorie
                                </th>
                                <th>
                                    Prix par jour
                                </th>

                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>
                                    Matricule
                                </th>
                                <th>
                                    Modele
                                </th>
                                <th>
                                    Categorie
                                </th>
                                <th>
                                    Prix par jour
                                </th>

                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.immat)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.modele.nom_modele)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.category.libelle_cat)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.prixJour)
                                </td>

                                <td>

                                    <span class="btn btn-primary text-light"><i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.idcar }, new { @style = "color:#fff;" })</span>
                                    <span class="btn btn-success"><i class="fas fa-list"></i>@Html.ActionLink("Details", "Details", new { id = item.idcar }, new { @style = "color:#fff;" }) </span>
                                    <span class="btn btn-danger"><i class="fas fa-trash-alt"></i>@Html.ActionLink("Delete", "Delete", new { id = item.idcar }, new { @style = "color:#fff;" })</span>
                                    <span class="btn btn-warning"><i class="fas fa-calendar"></i>@Html.ActionLink("Reservations", "ReservationsByCar", new { id = item.idcar }, new { @style = "color:#fff;" })</span>

                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

Views/voitures/ReservationsByCar.cshtml
@model IEnumerable<CarRental.Models.ReservationByCar_Result>

@{
    ViewBag.Title = "ReservationsByCar";
}

<h2>Reservations Par Voiture</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.objectif_reserv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kilometrage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_debut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_fin)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.objectif_reserv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kilometrage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date_debut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date_fin)
        </td>

    </tr>
}

</table>
<div>
    @Html.ActionLink("Revenir à la liste", "Index")
</div>