Models/marque.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public marque()
        {
            this.modeles = new HashSet<modele>();
        }
    
        public int idmarque { get; set; }
        public string nom_marque { get; set; }
        public string logo { get; set; }
        public string pays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modele> modeles { get; set; }
    }
}

Controllers/marquesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarRental.Models;
using CarRental.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CarRental.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class marquesController : Controller
    {
        private carrentalEntities db = new carrentalEntities();

        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());

                if (s[0].ToString() == "ADMIN")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
        // GET: reservations
        public ActionResult Index()
        {
            var user = User.Identity;
            if (isAdminUser())
            {
                ViewBag.Message = "ADMIN";
            }
            else
            {

                ViewBag.Message = user.Name;
            }
            return View(db.marques.ToList());
        }

        // GET: marques/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            marque marque = db.marques.Find(id);
            if (marque == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(marque);
        }

        // GET: marques/Create
        public ActionResult Create()
        {
            ViewBag.Message = "ADMIN";
            return View();
        }

        // POST: marques/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idmarque,nom_marque,pays,logo")] marque marque, HttpPostedFileBase file)
        {
            

             if (ModelState.IsValid)
             {
                 db.marques.Add(marque);
                 db.SaveChanges();
                 return RedirectToAction("Index");
             }
            ViewBag.Message = "ADMIN";
            return View(marque);
        }

        // GET: marques/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            marque marque = db.marques.Find(id);
            if (marque == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(marque);
        }

        // POST: marques/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idmarque,pays,nom_marque,logo")] marque marque)
        {
            if (ModelState.IsValid)
            {
                db.Entry(marque).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Message = "ADMIN";
            return View(marque);
        }

        // GET: marques/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            marque marque = db.marques.Find(id);
            if (marque == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = "ADMIN";
            return View(marque);
        }
        public ActionResult ModeleByMarques(int? id)
        {
            return View(db.ModeleByMarques(id).ToList());
        }

        // POST: marques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            marque marque = db.marques.Find(id);
            db.marques.Remove(marque);
            db.SaveChanges();
            ViewBag.Message = "ADMIN";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
     
    }
}

Views/marques/Create.cshtml
@model CarRental.Models.marque

@{
    ViewBag.Title = "Create";
}



<div class="card shadow mb-6" style="margin:0px 40px">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Ajouter 
        </h6>
    </div>
    <!-- /.container-fluid -->
    <div class="card-body " style="margin:0px 20px">
        @using (Html.BeginForm("Create", "marques", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="mb-3">
                @Html.TextBoxFor(model => model.nom_marque, new { placeholder = "Nom de la marque", @class = "form-control form-control-user" })
                @Html.ValidationMessageFor(model => model.nom_marque, "", new { @class = "text-danger" })
            </div>
            <div class="mb-3">
                @Html.TextBoxFor(m => m.pays, new { placeholder = "Pays", @class = "form-control form-control-user" })
                @Html.ValidationMessageFor(model => model.pays, "", new { @class = "text-danger" })
            </div>
            <div class="mb-3">
                @Html.TextBoxFor(m => m.logo, new { placeholder = "Logo", @class = "form-control form-control-user" })
                @Html.ValidationMessageFor(model => model.logo, "", new { @class = "text-danger" })
            </div>

            <div class="panel-footer">
                <button type="submit" class="btn btn-primary"><i class="fas fa-save">&nbsp;Enregistrer</i></button>
                <button type="reset" class="btn btn-danger"><i class="fas fa-undo">&nbsp;Annuler</i></button>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>


</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/marques/Delete.cshtml
@model CarRental.Models.marque

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Etes vous sure de supprimer cet élément?</h3>
<div>
    <h4>Marque</h4>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/marques/Details.cshtml
@model CarRental.Models.marque

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Marque</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.nom_marque)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.nom_marque)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.pays)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.pays)
        </dd>

        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.logo)
        </dt>

        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.logo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/marques/Edit.cshtml
@model CarRental.Models.marque

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Marque</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idmarque)

    <div class="mb-3">
        @Html.TextBoxFor(model => model.nom_marque, new { placeholder = "Nom de la marque", @class = "form-control form-control-user" })
        @Html.ValidationMessageFor(model => model.nom_marque, "", new { @class = "text-danger" })
    </div>
    <div class="mb-3">
        @Html.TextBoxFor(m => m.pays, new { placeholder = "Pays", @class = "form-control form-control-user" })
        @Html.ValidationMessageFor(model => model.pays, "", new { @class = "text-danger" })
    </div>
    <div class="mb-3">
        @Html.TextBoxFor(m => m.logo, new { placeholder = "Logo", @class = "form-control form-control-user" })
        @Html.ValidationMessageFor(model => model.logo, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/marques/Index.cshtml
@model IEnumerable<CarRental.Models.marque>

@{
    ViewBag.Title = "Index";
}

<h2>Marques</h2>

<span class="btn btn-light">
    <i class="fas fa-plus"></i>
    @Html.ActionLink("Create New", "Create", new { @style = "color:#fff;" })
</span>



<div class="container-fluid">
    <!-- DataTales Example -->

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                Liste des Marques
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%"
                       cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Nom Marque
                            </th>
                            <th>
                                Pays
                            </th>
                            <th>
                                Logo
                            </th>
                            <th>Actions</th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>

                            <th>
                                Nom Marque
                            </th>
                            <th>
                                Pays
                            </th>
                            <th>
                                Logo
                            </th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nom_marque)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.pays)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.logo)
                                </td>
                                <td>
                                  
                                        <span class="btn btn-primary text-light"><i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.idmarque }, new { @style = "color:#fff;" })</span> 
                                <span class="btn btn-success"><i class="fas fa-list"></i>@Html.ActionLink("Details", "Details", new { id = item.idmarque }, new { @style = "color:#fff;" }) </span>
                                <span class="btn btn-danger"><i class="fas fa-trash-alt"></i>@Html.ActionLink("Delete", "Delete", new { id = item.idmarque }, new { @style = "color:#fff;" })</span>
                                <span class="btn btn-warning"><i class="fas fa-car-alt"></i>@Html.ActionLink("Modele Par Marques", "ModeleByMarques", new { id = item.idmarque }, new { @style = "color:#fff;" })</span>
                     
                                </td>
                    </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

Views/marques/ModeleByMarques.cshtml
@model IEnumerable<CarRental.Models.ModeleByMarques_Result>
@{
    ViewBag.Title = "Modeles Par Marque";
}

<h2>Modele par marque</h2>

<p>
    @Html.ActionLink("Revenir", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_modele)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datesortie)
        </th>
        
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_modele)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datesortie)
        </td>
    </tr>
}

</table>